module.exports = {
    STATE_INIT: 'STATE_INIT',
    STATE_READY: 'STATE_READY',
    STATE_RUNNING: 'STATE_RUNNING',
    STATE_FINISHED: 'STATE_FINISHED',
    STATE_ERROR: 'STATE_ERROR',
    STATE_TIMED_OUT: 'STATE_TIMED_OUT'
};
